### ISSUE TITLE
Make the connection pool size parameters programmable

### ISSUE THREAD

**Issue by ahakanbaba** [wavefrontHQ/python-client#18]
Hi, 
In parallel usages with the async interface, the connection pool size of 4 can be a problem. 

An application that uses the async interface prints this warning 
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XXX.wavefront.com

It would be great to make the pools_size and maxsize parameters configurable here 
https://github.com/wavefrontHQ/python-client/blob/master/wavefront_api_client/rest.py#L61

**Comment by basilisk487** [comment]
@ahakanbaba You can actually change the connection pool size after initializing the client:

```
import wavefront_api_client as wave_api
from wavefront_api_client import rest
...
client = wave_api.ApiClient(host=base_url, header_name='Authorization', header_value='Bearer ' + api_key)
client.rest_client = wave_api.rest.RESTClientObject(pools_size=6, maxsize=6)
```

**Comment by ahakanbaba** [comment]
ok great I will try this.

**Comment by ahakanbaba** [comment]
@basilisk487 's Suggestion works and is very reasonable. Closing the issue.
