### ISSUE TITLE
Error using client with python 3.7

### ISSUE THREAD

**Issue by karlgoldstein** [wavefrontHQ/python-client#41]
We get this error when trying to use the api client with python 3.7:

```
    from wavefront_api_client import Dashboard, DashboardSection, DashboardSectionRow, \
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/__init__.py", line 19, in <module>
    from wavefront_api_client.api.alert_api import AlertApi
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api/__init__.py", line 6, in <module>
    from wavefront_api_client.api.alert_api import AlertApi
  File "/usr/local/lib/python3.7/site-packages/wavefront_api_client/api/alert_api.py", line 137
    async=params.get('async'),
        ^
SyntaxError: invalid syntax
```

Seems due to the fact that `async` is a reserved keyword as of python 3.7

**Comment by jbf-zuora** [comment]
Looks like its this bug: https://github.com/swagger-api/swagger-codegen/issues/8328

**Comment by soasme** [comment]
It seems that the package of version 2.3.2 hasn't yet been published to PyPI. 
@wavefrontHQ @basilisk487  Appreciate if you could release the package to PyPI. The latest package in PyPI still stays on version 2.3.1 https://pypi.org/project/wavefront-api-client/#history

**Comment by ustinov** [comment]
2.3.2 as on PyPI now https://pypi.org/project/wavefront-api-client/
