### ISSUE TITLE
Log metrics

### ISSUE THREAD

**Issue by beedub** [wavefrontHQ/python-client#5]
Is there a way to log metrics with this client?

**Comment by wavefront-mike** [comment]
Hi Brian -
Sorry for the delay.  There is not a way with the current client.  We do have a class that we use internally for sending metrics to the proxy.  I'm working on getting that class reviewed and will post it here shortly.

Mike M.
Wavefront Customer Success Team

**Comment by mspinassi** [comment]
I was about to ask the same thing.
@wavefront-mike do you know if it has been published somewhere?

**Comment by ustinov** [comment]
You may use `wavefront_pyformance` module for sending metrics into Wavefront.

https://github.com/wavefrontHQ/python-client/tree/master/wavefront_pyformance

**Comment by ustinov** [comment]
@beedub and @mspinassi, the metrics can be ingested using Direct Ingestion API
https://github.com/wavefrontHQ/python-client/blob/master/docs/DirectIngestionApi.md
