### ISSUE TITLE
Bug in get_dashboard

### ISSUE THREAD

**Issue by mdennehy** [wavefrontHQ/python-client#51]
Hi folks,
Seeing this when I try to use get_dashboard and a chart has a stacked area type: 
`Exception when calling DashboardApi: Invalid value for `stack_type` (bars), must be one of ['zero', 'expand', 'wiggle', 'silhouette']

ValueError("Invalid value for `stack_type` (bars), must be one of ['zero', 'expand', 'wiggle', 'silhouette']")`

My guess is that you activated the stacked column subtype of the stacked area chart for us and the library isn't ready for that type yet.

**Comment by mdennehy** [comment]
https://github.com/wavefrontHQ/python-client/pull/52

**Comment by ustinov** [comment]
Fixed in v2.33.15

https://github.com/wavefrontHQ/python-client/tree/v2.33.15
https://github.com/wavefrontHQ/python-client/blob/master/wavefront_api_client/models/chart_settings.py#L1317
